import type { Metadata } from "next";
import "./globals.css";
import { crimson, overpassMono, workSans } from "./_components/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${crimson.variable} ${workSans.variable} ${overpassMono.variable} font-serif`}>
      <body>{children}</body>
    </html>
  );
}
